<?php

########################################################################
# Extension Manager/Repository config file for ext: "pt_conference"
#
# Auto generated by Extbase Kickstarter 2010-08-29
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Conference Managment (extBase)',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Daniel Lienert',
	'author_email' => 'lienert@punkt.de',
	'author_company' => 'punkt.de',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid,pt_extlist',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.106',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
			'pt_extlist' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>